package ccs.markov.slicer;

public enum VariableTypes {
	
	PARAMETER,
	METHOD,
	LOCAL_VARIABLE,
	GLOBAL_VARIABLE,
	TRASITIVE_VARIABLE,
	CALLEE,
	CALLEE_THROUGH_PARAMETER,
	CALLEE_THROUGH_SCOPE_DEF,
	CALLEE_THROUGH_OBJECT_CREATION
}
